
import com.phenix.tools.swing.FileDrop;
import javax.swing.JOptionPane;

/**
 *
 * @author <a href="mailto:edouard128@hotmail.com">Edouard Jeanjean</a>
 */
public class Fenetre extends javax.swing.JFrame {

  /**
   * Creates new form Fenetre
   */
  public Fenetre() {
    initComponents();

    // On centre la fenêtre.
    super.setLocationRelativeTo(null);

    // <editor-fold defaultstate="collapsed" desc="Evenement détectant quand on dépose un fichier dans la fenêtre.">
    new FileDrop(this,
            files -> {
              try {
                new AdobePremiereProject(files[0], AdobePremiereProject.VERSION_CC2017_1_2);
              } catch (Exception ex) {
                ex.printStackTrace();
              }

            }
    );
    // </editor-fold>
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    L_drag_and_drop = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    L_drag_and_drop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    L_drag_and_drop.setText("<html>Drag and drop<br>\nVersion récente</html>");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(145, 145, 145)
        .addComponent(L_drag_and_drop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(158, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(123, 123, 123)
        .addComponent(L_drag_and_drop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(145, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel L_drag_and_drop;
  // End of variables declaration//GEN-END:variables
}
